# Autogenerated wrapper script for TracyProfiler_jll for i686-linux-musl-cxx11
export tracy_capture, tracy_csvexport, tracy_import_chrome, tracy_import_fuchsia, tracy_profiler, tracy_update

using FreeType2_jll
using Dbus_jll
using GLFW_jll
using LibCURL_jll
using Xorg_libX11_jll
using Xorg_libXrandr_jll
using Xorg_libXinerama_jll
using Xorg_libXcursor_jll
using Xorg_libXi_jll
JLLWrappers.@generate_wrapper_header("TracyProfiler")
JLLWrappers.@declare_executable_product(tracy_capture)
JLLWrappers.@declare_executable_product(tracy_csvexport)
JLLWrappers.@declare_executable_product(tracy_import_chrome)
JLLWrappers.@declare_executable_product(tracy_import_fuchsia)
JLLWrappers.@declare_executable_product(tracy_profiler)
JLLWrappers.@declare_executable_product(tracy_update)
function __init__()
    JLLWrappers.@generate_init_header(FreeType2_jll, Dbus_jll, GLFW_jll, LibCURL_jll, Xorg_libX11_jll, Xorg_libXrandr_jll, Xorg_libXinerama_jll, Xorg_libXcursor_jll, Xorg_libXi_jll)
    JLLWrappers.@init_executable_product(
        tracy_capture,
        "bin/tracy-capture",
    )

    JLLWrappers.@init_executable_product(
        tracy_csvexport,
        "bin/tracy-csvexport",
    )

    JLLWrappers.@init_executable_product(
        tracy_import_chrome,
        "bin/tracy-import-chrome",
    )

    JLLWrappers.@init_executable_product(
        tracy_import_fuchsia,
        "bin/tracy-import-fuchsia",
    )

    JLLWrappers.@init_executable_product(
        tracy_profiler,
        "bin/tracy-profiler",
    )

    JLLWrappers.@init_executable_product(
        tracy_update,
        "bin/tracy-update",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
