# Autogenerated wrapper script for TracyProfiler_jll for i686-w64-mingw32-cxx11
export capture, csvexport, import_chrome, tracy, update

using Capstone_jll
using FreeType2_jll
using GLFW_jll
JLLWrappers.@generate_wrapper_header("TracyProfiler")
JLLWrappers.@declare_executable_product(capture)
JLLWrappers.@declare_executable_product(csvexport)
JLLWrappers.@declare_executable_product(import_chrome)
JLLWrappers.@declare_executable_product(tracy)
JLLWrappers.@declare_executable_product(update)
function __init__()
    JLLWrappers.@generate_init_header(Capstone_jll, FreeType2_jll, GLFW_jll)
    JLLWrappers.@init_executable_product(
        capture,
        "bin\\tracy-capture.exe",
    )

    JLLWrappers.@init_executable_product(
        csvexport,
        "bin\\tracy-csvexport.exe",
    )

    JLLWrappers.@init_executable_product(
        import_chrome,
        "bin\\tracy-import-chrome.exe",
    )

    JLLWrappers.@init_executable_product(
        tracy,
        "bin\\tracy.exe",
    )

    JLLWrappers.@init_executable_product(
        update,
        "bin\\tracy-update.exe",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
