# Autogenerated wrapper script for TracyProfiler_jll for i686-w64-mingw32-cxx11
export tracy, tracy_capture, tracy_csvexport, tracy_import_chrome, tracy_import_fuchsia, tracy_update

using FreeType2_jll
using GLFW_jll
using LibCURL_jll
JLLWrappers.@generate_wrapper_header("TracyProfiler")
JLLWrappers.@declare_executable_product(tracy)
JLLWrappers.@declare_executable_product(tracy_capture)
JLLWrappers.@declare_executable_product(tracy_csvexport)
JLLWrappers.@declare_executable_product(tracy_import_chrome)
JLLWrappers.@declare_executable_product(tracy_import_fuchsia)
JLLWrappers.@declare_executable_product(tracy_update)
function __init__()
    JLLWrappers.@generate_init_header(FreeType2_jll, GLFW_jll, LibCURL_jll)
    JLLWrappers.@init_executable_product(
        tracy,
        "bin\\tracy.exe",
    )

    JLLWrappers.@init_executable_product(
        tracy_capture,
        "bin\\tracy-capture.exe",
    )

    JLLWrappers.@init_executable_product(
        tracy_csvexport,
        "bin\\tracy-csvexport.exe",
    )

    JLLWrappers.@init_executable_product(
        tracy_import_chrome,
        "bin\\tracy-import-chrome.exe",
    )

    JLLWrappers.@init_executable_product(
        tracy_import_fuchsia,
        "bin\\tracy-import-fuchsia.exe",
    )

    JLLWrappers.@init_executable_product(
        tracy_update,
        "bin\\tracy-update.exe",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
